authorization:
    in: header
    description: Bearer token
    name: Authorization
    schema:
        type: string
    required: true
id:
    in: path
    description: User id
    name: id
    schema:
        type: string
    required: true
